### ISSUE TITLE
Helper contains app specific behaviour

### ISSUE THREAD

**Issue by mikecmpbll** [meritec/awesome_sort#1]
Including `search` param in `column_sort` links isn't necessary for the gem. The gem API should allow for additional params to be passed in via opts to the `column_sort` method.

https://github.com/meritec/awesome_sort/blob/master/app/helpers/awesome_sort/awesome_sort_helper.rb#L24

**Comment by AndrewOS95** [comment]
Issue resolved. 

The API now allows for additional parameters to be passed.
